max_width = 80
tab_spaces = 2
newline_style = "Unix"
edition = "2021"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
merge_derives = true
use_field_init_shorthand = true
